;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-buffer
        helm-M-x
        helm-projectile-switch-project
        js2-mode-show-node
        save-some-buffers
        sp-kill-word
        ))

(setq mc/cmds-to-run-once
      '(
        prelude-move-beginning-of-line
        sp-backward-delete-char
        sp-delete-char
        ))
